### PR TITLE
Make all tests run on Python 3.

### PR DESCRIPTION
**Pull request by ProgVal**
Assumptions:
* You merged #2 
* You have a recent version of gevent installed (the current version in pip does not work, but the master branch of https://github.com/gevent/gevent does)
* You have dnspython3 installed. (dnspython does not work on Python 3)

### CODE REVIEW

**Comment by abesto** [comment]
Great stuff!

I'd prefer not to add a dependency on `gevent` HEAD, and as far as I can tell there is no estimate on when `gevent` will be considered stable on py3. There are some promising alternatives, at a glance `asyncio` and `circuits` look like they can do everything `python-ircd` uses from `gevent`.

The integration with `gevent` is very thin, so trying another networking / threading lib shouldn't be too hard. How do you feel about trying that in another PR? Then this one could be trivially merged, and boom, `python-ircd` is py3 compatible.

**Comment by ProgVal** [comment]
Python 2 will still work with a stable version of gevent, so this pull request does not introduce any regression.

I might work on porting the code to another library some day; but I prefer not to do that now as I have no experience with these libraries *and* your code

**Comment by abesto** [comment]
Fair enough. Please split up `requirements.txt` into `requirements-{common,python2,python3}.txt` files, where `requirements-python3.txt` has the stuff required to run on python3 (pinned to a `gevent` version that works like `-e git://github.com/gevent/gevent@COMMITSHA#egg=gevent`), and I'll merge this.

**Comment by ProgVal** [comment]
Done.

**Comment by abesto** [comment]
Thanks for the great work! :+1:

**Pull request merged**
